	name: Auto Deploy to Netlify
	
	on:
	  push:
	    branches: ["development-inProgress"]
	  workflow_dispatch:
	
	jobs:
	  auto-deploy:
	    runs-on: ubuntu-latest
	    steps:
	      - name: Checkout the repository
	        uses: actions/checkout@v3
	      - name: Install Node and NPM
	        uses: actions/setup-node@v3
	        with:
	          node-version: '16'
      - name: Install necessary packages
	        run: npm install --legacy-peer-deps
	      - name: Build the project
            run: npm run build
